<?php
////////////////////////////////////////////////////////////////////////////////
//   Copyright (C) Hakkah~CMS Development Team                                //
//   http://hakkahcms.sourceforge.net                                         //
//                                                                            //
//   This program is distributed in the hope that it will be useful,          //
//   but WITHOUT ANY WARRANTY, without even the implied warranty of           //
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                     //
//                                                                            //
//   This product released under GNU General Public License v2                //
////////////////////////////////////////////////////////////////////////////////

// iBlocks guide module // for developers
$result = ''; // html code generated by module

// Getting listing of iblocks
$iblock = new iBlock(); // loads iblocks structure if not loaded [RECOMMENDED]
$ibids = array_keys($system->iblocks); // var_dump($system->iblocks); // this array is associated (<ibid> => <iblock data>)
$count = sizeof($ibids); // iblocks count
for($i=0; $i<$count; $i++)
{
	// $fields = unpack_data($system->iblocks[$ibids[$i]]['fields']); // packed iblock fields options
	// $extopt = unpack_data($system->iblocks[$ibids[$i]]['extopt']); // packed iblock extended options
	$result .= '#'.($i+1).' <b>'.$system->iblocks[$ibids[$i]]['title'].'</b> ['.$system->iblocks[$ibids[$i]]['ibid'].'] - '.$system->iblocks[$ibids[$i]]['description'].'<br>';
}
// listings of iblock groups and containers are similar

show_window('',$result);
?>